version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: my-sql-db
    environment:
      POSTGRES_USER: sql
      POSTGRES_PASSWORD: sql
      POSTGRES_DB: sql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
